<?php

/**
 * @file
 * Contains linky.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function linky_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linky module.
    case 'help.page.linky':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Link management Drupal 8 style') . '</p>';
      return $output;

    default:
  }
}
