# Schema for the configuration files of the Linky module.

field.widget.settings.linky:
  type: field.widget.settings.dynamic_entity_reference_default
  label: 'Linky autocomplete widget display format settings'
  mapping:
    allow_duplicate_urls:
      type: boolean
      label: 'Allow duplicate urls'
